[Draft] Add pagination client support to project and violations endpoint
jetstack/dependency-track-exporter pull request #25
Opened 2022-10-21 08:58 UTC by jakoberpf

Hello Everyone,

this PR wants to add support for pagination pulling from DT, as its endpoint only return a max of a 100 items per request. Therefore if you have more than a 100 projects or violations, your metrics result will be incomplete. 

There are two endpoints used in the exporter which are relevant for this `api/v1/projects` and `api/v1/violations`. In this PR we add an iterative logic to the client, where it will iterates over increasing pagination pages until there are not items returned any more. This way we can get all items from a resource. 

The major downside which we see right now and a looking to fix is the request duration when (like in our case) you have about 60.000 violations spread about a hundrets of projects. Goal would be to make pulling the violations optional from the `/metrics` endpoint.

Any feedback would be appreciated

2022-11-11 13:33 UTC, ribbybibby commented on internal/dependencytrack/policy.go
> +		if len(req) == 0 {
The number of total items will not necessarily be a multiple of 100, which means the 'last page' will have less than 100 results. 

If we change this check to `len(req) < 100` (and move some of the logic around) I think we can avoid an extra request to the API in most cases.

2022-11-11 13:35 UTC, ribbybibby commented on internal/dependencytrack/policy.go
> +	foundAll := false
```suggestion
// GetAllViolations returns violations for the entire portfolio. Suppressed
// violations are omitted unless suppressed is true
func (c *Client) GetAllViolations(suppressed bool) ([]*PolicyViolation, error) {
	allPolicyViolations := []*PolicyViolation{}
	lastPaginationPage := 1
	foundAll := false
```

nit: I don't think the comments are necessary. I think it's clear enough from the code.

2022-11-11 13:37 UTC, ribbybibby commented on internal/dependencytrack/project.go
> +	foundAll := false
```suggestion
// GetAllProjects returns a list of all projects
func (c *Client) GetAllProjects() ([]*Project, error) {
	allProjects := []*Project{}
	lastPaginationPage := 1
	foundAll := false
```

nit: I don't think the comments are necessarily. It's clear enough from the code.

2022-11-11 13:38 UTC, ribbybibby commented on internal/dependencytrack/project.go
> +		if len(req) == 0 {
The number of total items will not necessarily be a multiple of 100, which means the 'last page' will have less than 100 results. 

If we change this check to `len(req) < 100` (and move some of the logic around) I think we can avoid an extra request to the API in most cases.

2022-11-11 13:39 UTC, ribbybibby requested changes
Thank you for this pull request! Glad to see that you're using the exporter.

On the whole this looks really good to me. I've just left a couple of nitpicks and one suggestion for the pagination logic.

2022-11-11 13:44 UTC, ribbybibby commented
I've opened an issue for the request duration: https://github.com/jetstack/dependency-track-exporter/issues/30

2022-11-11 13:47 UTC, jakoberpf commented
@ribbybibby great, thanks for you feedback, really good stuff. Will implement these next week.

2022-12-02 09:40 UTC, ribbybibby commented
Pagination came along with https://github.com/jetstack/dependency-track-exporter/pull/33, so I'm going to close this PR. Thank you very much for the time you spent on it though, @jakoberpf. 

I'm going to cut a 0.2.0 release with these changes soon. When that drops it would be great if you could upgrade and provide some stats on #30 in terms of the request duration you see to the exporter and the number of projects and violations you have in your DT instance.

I'm really interested in making this exporter as usable and performant as possible but I don't personally run a very large DT instance, so your insight would be very valuable.

2022-12-02 09:40 UTC, closed without merging

2022-12-02 10:07 UTC, jakoberpf commented
@ribbybibby Oh great, sorry that I didn't came around to make the changes before. I will post some metrics with the new version, when is there :-) I am on holiday til mid Jan, from next week, though.