Fix required permission to run the exporter
jetstack/dependency-track-exporter pull request #46
Opened 2023-01-30 16:13 UTC by sergioasantiago

2023-02-01 18:46 UTC, ribbybibby requested changes
Thanks for the PR!

Looks good to me but can you remove the `dependency-track-exporter` binary?

2023-02-02 09:47 UTC, sergioasantiago commented
Done.

2023-02-02 10:01 UTC, sergioasantiago commented
> 

Removed.

2023-02-06 09:11 UTC, ribbybibby approved these changes

2023-02-06 09:11 UTC, merged