Enhance Dockerfile adding multistage build
jetstack/dependency-track-exporter pull request #47
Opened 2023-01-31 10:19 UTC by sergioasantiago

2023-02-01 18:41 UTC, ribbybibby commented
Thanks for the PR!

The Dockerfile is designed to work with goreleaser which we use to produce our releases. This is why it copies the binary into the container.

That being said, I do think it is valuable to have a Dockerfile that you can build with `docker build` when testing. So perhaps, in addition to the changes in this PR, we should rename the current Dockerfile to Dockerfile.goreleaser and modify goreleaser to use that.

2023-02-01 18:51 UTC, ribbybibby commented on Dockerfile
> +FROM gcr.io/distroless/base-debian11:latest-amd64
Could we use `gcr.io/distroless/static:nonroot` here? Unless there's a reason we need debian, I'd prefer to use the most minimal possible image.

2023-02-01 18:53 UTC, ribbybibby requested changes
One comment about the base image. And, as mentioned, we should use the existing Dockerfile with `goreleaser`.

2023-02-02 10:22 UTC, sergioasantiago commented
> One comment about the base image. And, as mentioned, we should use the existing Dockerfile with `goreleaser`.

Thanks for your comment, Changes have been made.

2023-02-06 09:16 UTC, ribbybibby approved these changes

2023-02-06 09:17 UTC, merged